"""AGENTS.md auto-generator — introspects agent modules to produce documentation."""

from __future__ import annotations

import importlib
import inspect
import logging
import re
from dataclasses import dataclass, field

log = logging.getLogger(__name__)

AGENT_MODULES = [
    "theswarm.agents.po",
    "theswarm.agents.techlead",
    "theswarm.agents.dev",
    "theswarm.agents.qa",
]

_TOOL_MODULES = {"github", "claude", "git"}


@dataclass(frozen=True)
class AgentInfo:
    """Metadata extracted from a single agent module."""

    name: str
    module_path: str
    nodes: list[str] = field(default_factory=list)
    tools_used: list[str] = field(default_factory=list)
    description: str = ""


# ── Introspection ─────────────────────────────────────────────────


def _extract_nodes(source: str) -> list[str]:
    """Parse ``add_node("name", ...)`` calls from function source."""
    return re.findall(r'add_node\(\s*["\']([^"\']+)["\']', source)


def _extract_tools(source: str) -> list[str]:
    """Detect tool imports (github, claude, git) in module source."""
    found: list[str] = []
    for tool in sorted(_TOOL_MODULES):
        if re.search(rf"theswarm\.tools\.{tool}\b", source):
            found.append(tool)
    return found


def _find_graph_builder(module: object) -> str | None:
    """Return source of the ``build_*_graph`` function if present."""
    for name, obj in inspect.getmembers(module, inspect.isfunction):
        if name.startswith("build_") and name.endswith("_graph"):
            try:
                return inspect.getsource(obj)
            except OSError:
                return None
    return None


def introspect_agents(
    module_paths: list[str] | None = None,
) -> list[AgentInfo]:
    """Introspect all agent modules and extract graph info.

    For each module:
    1. Import it
    2. Find the ``build_*_graph()`` function
    3. Extract node names from the function source (``add_node`` calls)
    4. Find tool imports (github, claude, git)
    5. Extract the module docstring as description
    """
    paths = module_paths or AGENT_MODULES
    agents: list[AgentInfo] = []

    for mod_path in paths:
        try:
            mod = importlib.import_module(mod_path)
        except ImportError:
            log.warning("Could not import agent module: %s", mod_path)
            continue

        # Module-level description
        description = (inspect.getdoc(mod) or "").strip()

        # Full module source for tool detection
        try:
            full_source = inspect.getsource(mod)
        except OSError:
            full_source = ""

        # Graph builder source for node extraction
        builder_source = _find_graph_builder(mod) or ""
        nodes = _extract_nodes(builder_source)
        tools = _extract_tools(full_source)

        # Derive a short name from the module path  (e.g. "po", "techlead")
        name = mod_path.rsplit(".", maxsplit=1)[-1]

        agents.append(
            AgentInfo(
                name=name,
                module_path=mod_path,
                nodes=nodes,
                tools_used=tools,
                description=description,
            )
        )

    return agents


# ── Markdown generation ───────────────────────────────────────────

_PIPELINE_OVERVIEW = (
    "PO (morning) \u2192 TechLead (breakdown) \u2192 Dev (implement) "
    "\u2192 TechLead (review) \u2192 QA (test + demo) \u2192 PO (evening)"
)

_STATE_FIELDS = [
    ("team_id", "Team identifier"),
    ("github_repo", "Target GitHub repository (owner/repo)"),
    ("phase", "Current pipeline phase"),
    ("task", "Active task dict (title, body, number)"),
    ("branch", "Git branch name for the current work"),
    ("context", "Loaded project context (README, CLAUDE.md, etc.)"),
    ("result", "Agent result text"),
    ("tokens_used", "Cumulative token count"),
    ("cost_usd", "Estimated API cost"),
    ("tests_passed", "Whether unit tests passed"),
    ("demo_report", "QA demo report dict"),
]


def generate_agents_md(agents: list[AgentInfo] | None = None) -> str:
    """Generate AGENTS.md content from introspected agent info.

    Builds a markdown document with:
    - Header
    - Pipeline overview (PO -> TechLead -> Dev -> QA)
    - Per-agent sections with nodes, tools, description
    - State schema (AgentState fields)
    - Configuration section
    """
    if agents is None:
        agents = introspect_agents()

    lines: list[str] = [
        "# AGENTS.md",
        "",
        "> Auto-generated by `theswarm.tools.agents_md`. Do not edit manually.",
        "",
        "## Pipeline Overview",
        "",
        _PIPELINE_OVERVIEW,
        "",
    ]

    # Per-agent sections
    for agent in agents:
        title = agent.name.upper() if len(agent.name) <= 2 else agent.name.capitalize()
        lines.append(f"## {title} Agent")
        lines.append("")
        if agent.description:
            lines.append(agent.description)
            lines.append("")
        lines.append(f"**Module:** `{agent.module_path}`")
        lines.append("")
        if agent.nodes:
            lines.append("**Graph nodes:**")
            for node in agent.nodes:
                lines.append(f"- `{node}`")
            lines.append("")
        if agent.tools_used:
            lines.append(f"**Tools:** {', '.join(f'`{t}`' for t in agent.tools_used)}")
            lines.append("")

    # State schema
    lines.append("## State Schema (`AgentState`)")
    lines.append("")
    lines.append("| Field | Description |")
    lines.append("|-------|-------------|")
    for field_name, desc in _STATE_FIELDS:
        lines.append(f"| `{field_name}` | {desc} |")
    lines.append("")

    # Configuration
    lines.append("## Configuration")
    lines.append("")
    lines.append(
        "Agent behavior is configured via `CycleConfig` in `theswarm.config`. "
        "Token budgets, model selection, and workspace directory are all "
        "configurable per-cycle."
    )
    lines.append("")

    return "\n".join(lines)
