"""Ports (interfaces) of the Customers context."""

from __future__ import annotations

from typing import Protocol

from theswarm.domain.customers.entities import Customer, Member
from theswarm.domain.customers.requests import Request


class CustomerRepository(Protocol):
    async def get(self, customer_id: str) -> Customer | None: ...
    async def get_by_slug(self, slug: str) -> Customer | None: ...
    async def list_all(self) -> list[Customer]: ...
    async def save(self, customer: Customer) -> None: ...
    async def delete(self, customer_id: str) -> None: ...


class MemberRepository(Protocol):
    async def get(self, member_id: str) -> Member | None: ...
    async def list_for_customer(self, customer_id: str) -> list[Member]: ...
    async def find_by_email(self, customer_id: str, email: str) -> Member | None: ...
    async def find_by_github_login(self, login: str) -> Member | None: ...
    async def find_by_invite_token_hash(self, token_hash: str) -> Member | None: ...
    async def save(self, member: Member) -> None: ...


class RequestRepository(Protocol):
    async def get(self, request_id: str) -> Request | None: ...
    async def list_for_customer(self, customer_id: str, limit: int = 50) -> list[Request]: ...
    async def list_inbox(self, limit: int = 50) -> list[Request]: ...
    async def list_open(self, limit: int = 200) -> list[Request]: ...
    async def list_by_feature(self, repo: str, issue_number: int) -> list[Request]: ...
    async def save(self, request: Request) -> None: ...
